# Generated by Django 5.1.3 on 2026-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_patient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=10)),
                ('from_number', models.CharField(blank=True, max_length=32, null=True)),
                ('to_number', models.CharField(blank=True, max_length=32, null=True)),
                ('body', models.TextField(blank=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

