# Generated by Django 5.1.3 on 2024-12-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='availableslot',
            unique_together=set(),
        ),
    ]
